import { Router } from 'express';
import { getAllRestaurants, getPlatformAnalytics, updatePlan, toggleRestaurant, updateUserRole, getAllUsers, exportRestaurants, exportOrders, getPopularItems, bulkUpdateUserRoles, bulkActivateUsers, getGeographicDistribution }
  from '../controllers/platform.controller.js';
import { getActivityLogs, getActivitySummary } from '../controllers/activity.controller.js';
import { getPlanLimits, updatePlanLimits } from '../controllers/planLimits.controller.js';
import { getFeatureFlags, updateFeatureFlag } from '../controllers/featureFlags.controller.js';
import { getEmailTemplates, getEmailTemplate, updateEmailTemplate, previewEmailTemplate, sendTestEmail } from '../controllers/emailTemplates.controller.js';
import { getAnnouncements, createAnnouncement, updateAnnouncement, deleteAnnouncement } from '../controllers/announcements.controller.js';
import { getSupportTickets, updateTicket, getTicketStats } from '../controllers/supportTickets.controller.js';
import { getOnboardingItems, createOnboardingItem, updateOnboardingItem, deleteOnboardingItem, getOnboardingOverview } from '../controllers/onboarding.controller.js';
import { getTrials, getTrialStats, startTrial, convertTrial, extendTrial, getTrialEngagement } from '../controllers/trialManagement.controller.js';
import { getRevenueAnalytics, getMrrHistory, getUpgradeAnalysis, recordRevenueEvent, createMrrSnapshot } from '../controllers/revenueAnalytics.controller.js';
import { getReferrals, getReferralStats, markReferralConverted, payReferralReward, updateReferralCode } from '../controllers/referralProgram.controller.js';
import { authenticate, authorizeRole } from '../middleware/authenticate.js';

const router = Router();
router.use(authenticate, authorizeRole('platform_admin'));

router.get('/restaurants', getAllRestaurants);
router.get('/analytics', getPlatformAnalytics);
router.get('/users', getAllUsers);
router.get('/export/restaurants', exportRestaurants);
router.get('/export/orders', exportOrders);
router.get('/activity-logs', getActivityLogs);
router.get('/activity-logs/summary', getActivitySummary);
router.get('/plan-limits', getPlanLimits);
router.patch('/plan-limits/:plan', updatePlanLimits);
router.get('/popular-items', getPopularItems);
router.get('/geography', getGeographicDistribution);
router.get('/feature-flags', getFeatureFlags);
router.patch('/feature-flags/:key', updateFeatureFlag);
router.get('/email-templates', getEmailTemplates);
router.get('/email-templates/:key', getEmailTemplate);
router.patch('/email-templates/:key', updateEmailTemplate);
router.post('/email-templates/:key/preview', previewEmailTemplate);
router.post('/email-templates/:key/send-test', sendTestEmail);
router.get('/announcements', getAnnouncements);
router.post('/announcements', createAnnouncement);
router.patch('/announcements/:id', updateAnnouncement);
router.delete('/announcements/:id', deleteAnnouncement);
router.get('/support-tickets', getSupportTickets);
router.get('/support-tickets/stats', getTicketStats);
router.patch('/support-tickets/:id', updateTicket);
router.get('/onboarding-items', getOnboardingItems);
router.post('/onboarding-items', createOnboardingItem);
router.patch('/onboarding-items/:id', updateOnboardingItem);
router.delete('/onboarding-items/:id', deleteOnboardingItem);
router.get('/onboarding/overview', getOnboardingOverview);
router.get('/trials', getTrials);
router.get('/trials/stats', getTrialStats);
router.post('/trials', startTrial);
router.post('/trials/:id/convert', convertTrial);
router.post('/trials/:id/extend', extendTrial);
router.get('/trials/:id/engagement', getTrialEngagement);
router.get('/revenue/analytics', getRevenueAnalytics);
router.get('/revenue/mrr-history', getMrrHistory);
router.get('/revenue/upgrades', getUpgradeAnalysis);
router.post('/revenue/events', recordRevenueEvent);
router.post('/revenue/snapshot', createMrrSnapshot);
router.get('/referrals', getReferrals);
router.get('/referrals/stats', getReferralStats);
router.post('/referrals/:id/mark-converted', markReferralConverted);
router.post('/referrals/:id/pay-reward', payReferralReward);
router.patch('/referral-codes/:id', updateReferralCode);
router.patch('/restaurants/:id/plan', updatePlan);
router.patch('/restaurants/:id/toggle', toggleRestaurant);
router.patch('/users/:id/role', updateUserRole);
router.post('/users/bulk-update-role', bulkUpdateUserRoles);
router.post('/users/bulk-activate', bulkActivateUsers);

export default router;
